// <auto-generated />
namespace TryBeta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class connectParticpantEvaluationStatusIdtoProgramPlanStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(connectParticpantEvaluationStatusIdtoProgramPlanStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202508280439529_connect ParticpantEvaluation StatusId to ProgramPlanStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
