// <auto-generated />
namespace TryBeta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addAPIGETUsersProgram : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAPIGETUsersProgram));
        
        string IMigrationMetadata.Id
        {
            get { return "202508180717430_add API GET Users Program"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
