// <auto-generated />
namespace TryBeta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class fixParticipantEvaluationStatusId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixParticipantEvaluationStatusId2));
        
        string IMigrationMetadata.Id
        {
            get { return "202508191433106_fix ParticipantEvaluation StatusId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
