// <auto-generated />
namespace TryBeta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class fixParticipantEvaluationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixParticipantEvaluationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202508271250209_fix ParticipantEvaluation Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
