// <auto-generated />
namespace TryBeta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class adjustcommentinParticipantEvaluation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustcommentinParticipantEvaluation));
        
        string IMigrationMetadata.Id
        {
            get { return "202508271450120_adjust comment in ParticipantEvaluation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
